# Generated by Django 2.1.7 on 2019-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20190320_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
