# Generated by Django 2.1.7 on 2019-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20190322_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinates',
            field=models.CharField(default='', max_length=30),
        ),
    ]
