# Generated by Django 2.1.7 on 2019-03-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0012_auto_20190322_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutme',
            field=models.CharField(default='', max_length=140),
        ),
    ]
