# Generated by Django 2.1.7 on 2019-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0013_user_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
