# Generated by Django 2.1.7 on 2019-03-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0014_user_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.OrderItems'),
        ),
    ]
