# Generated by Django 2.1.7 on 2019-03-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0021_auto_20190325_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Item'),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Item'),
        ),
    ]
