# Generated by Django 2.1.7 on 2019-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0024_auto_20190329_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
