# Generated by Django 2.1.7 on 2019-04-01 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('API', '0025_auto_20190329_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiftlyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_alias', models.EmailField(blank=True, default='', max_length=70)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='locationitem',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',)},
        ),
    ]
