# Generated by Django 2.1.7 on 2019-04-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0026_auto_20190401_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiftlygroup',
            name='group',
        ),
        migrations.DeleteModel(
            name='SwiftlyGroup',
        ),
    ]
