# Generated by Django 2.1.7 on 2019-04-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0028_remove_user_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuplocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
