# Generated by Django 2.2 on 2019-04-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0029_auto_20190401_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
