# Generated by Django 2.2 on 2019-04-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0030_auto_20190409_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
