# Generated by Django 2.2 on 2019-04-10 12:00

import SwiftlyAPI.API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0031_auto_20190410_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=SwiftlyAPI.API.models.get_image_path),
        ),
    ]
