# Generated by Django 2.2 on 2019-04-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0032_auto_20190410_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
