# Generated by Django 2.2 on 2019-04-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0036_auto_20190410_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
